#**NUMPY - 1º Abrindo a Documentação da Biblioteca**

Procurar no motor de busca: NumPy

Procurar docomentação básica para inciantes

# **NUMPY - 2º Qual a diferença entre NumPy e listas?"**

Comparar performance entre list e array::

In [1]:
import numpy as np
num_elementos = 1000000000
teste_memoria_lista = []
# for x in range (num_elementos):
#   teste_memoria_lista.append(num_elementos)

teste_memoria_array = np.arange(num_elementos) 

#**NUMPY - 3º Criar um arrays simples com numpy**

Utilizar:

.array/.zeros/.ones/.empty/.arrange/.linespace

In [2]:
import numpy as np

print("Array criado com o método .array") 
print(np.array([2,3,4]))
print("Array criado com o método .zeros") 
print(np.zeros(10))
print("Array criado com o método .ones") 
print(np.ones(10))
print("Array criado com o método .empty") 
print(np.empty(10))
print("Array criado com o método .arange") 
print(np.arange(10))
print("Array criado com o método .linespace") 
print(np.linspace(0,40, num = 21))

Array criado com o método .array
[2 3 4]
Array criado com o método .zeros
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array criado com o método .ones
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array criado com o método .empty
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array criado com o método .arange
[0 1 2 3 4 5 6 7 8 9]
Array criado com o método .linespace
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34.
 36. 38. 40.]


#**NUMPY - 4º A importância de se definir os tipo de dado**

COMPARAR PERFORMANCE INT8 com FLOAT64

In [3]:
import numpy as np
num_elementos = 1000000000
# teste_performance = np.ones(num_elementos)
teste_performance = np.ones(num_elementos, dtype = np.int8)
print(teste_performance)

[1 1 1 ... 1 1 1]


#**NUMPY - 5º Criando um vetor de números randômicos**

In [4]:
import numpy as np
rng = np.random.default_rng()
print(rng.random(3))

[0.2943053  0.89963442 0.61777695]


#**NUMPY - 6º Vetor vs Matriz vs Tensor**

In [5]:
import numpy as np
rng = np.random.default_rng()
print("\n\nEste é um vetor 1's de tamanho 10")
vetor = rng.random((3))
print(vetor)
print("\n\nEsta é uma matriz 1's de tamanho 10")
matriz = rng.random((3,3))
print(matriz)
print("\n\nEste é um tensor 1's de tamanho 10")
tensor = rng.random((3,3,3))
print(tensor)



Este é um vetor 1's de tamanho 10
[0.59048267 0.67588083 0.67811516]


Esta é uma matriz 1's de tamanho 10
[[0.87024857 0.7188217  0.80646269]
 [0.91012274 0.43832168 0.95639758]
 [0.34595483 0.27241444 0.1228725 ]]


Este é um tensor 1's de tamanho 10
[[[0.3695475  0.11783462 0.95538417]
  [0.51708363 0.38754987 0.50710426]
  [0.85549134 0.87396797 0.29773021]]

 [[0.05429097 0.27942646 0.31248953]
  [0.53311    0.02771237 0.37948282]
  [0.51480459 0.42596289 0.69910384]]

 [[0.93574234 0.32703368 0.40361999]
  [0.41107559 0.38956718 0.98087605]
  [0.56719279 0.0688883  0.11356838]]]


#**NUMPY - 7º Ordenar e Adicionar num array**




In [2]:
import numpy as np
rng = np.random.default_rng()
array_rng1 = rng.random((2,3))
#Ordenação
print("\nArray SEM ordenação")
print(array_rng1)
array_ordenado = np.sort(array_rng1)
print("\nArray COM ordenação")
print(array_ordenado)
#Concatenação
array_rng2 = rng.random((2,1))
print("\nArray 2 tamanho 1 por 3")
print(array_rng2)
array_concatenado = np.concatenate((array_ordenado,array_rng2), axis=1)
print("\n 1º Maneira de concatenar entre arrays")
print(array_concatenado)

array_concatenado2 = np.hstack((array_ordenado,array_rng2))
print("\n 2º Maneira de concatenar entre arrays")
print(array_concatenado2)


Array SEM ordenação
[[0.3423374  0.30695589 0.56321862]
 [0.39628385 0.32719344 0.29397759]]

Array COM ordenação
[[0.30695589 0.3423374  0.56321862]
 [0.29397759 0.32719344 0.39628385]]

Array 2 tamanho 1 por 3
[[0.94317546]
 [0.64388733]]

 1º Maneira de concatenar entre arrays
[[0.30695589 0.3423374  0.56321862 0.94317546]
 [0.29397759 0.32719344 0.39628385 0.64388733]]

 2º Maneira de concatenar entre arrays
[[0.30695589 0.3423374  0.56321862 0.94317546]
 [0.29397759 0.32719344 0.39628385 0.64388733]]


#**NUMPY - 8 Como saber o formato de um array**

In [7]:
import numpy as np
rng = np.random.default_rng()
array_rng1 = rng.random((12,23,24))
print(array_rng1)


print("\nO número de dimensões")
print(array_rng1.ndim)
print("\nO número de elementos")
print(array_rng1.size)
print("\nO formato do array")
print(array_rng1.shape)

[[[0.39842841 0.26521295 0.43601087 ... 0.60355522 0.43060557 0.92216021]
  [0.15783249 0.03534512 0.49655728 ... 0.18624639 0.05477226 0.1861091 ]
  [0.07277541 0.05689489 0.55344123 ... 0.16211814 0.44625952 0.39094277]
  ...
  [0.70643951 0.71670478 0.72963996 ... 0.22265662 0.16805519 0.3047643 ]
  [0.62568714 0.3359426  0.92674112 ... 0.07105203 0.44479769 0.07516334]
  [0.40744723 0.29481667 0.9265563  ... 0.35756933 0.36485624 0.77343317]]

 [[0.25859914 0.51843776 0.68683711 ... 0.97950235 0.57157009 0.40854311]
  [0.26046218 0.79056975 0.39138889 ... 0.86680239 0.37487491 0.74010432]
  [0.04266486 0.41336427 0.95917515 ... 0.51669817 0.3664584  0.55317784]
  ...
  [0.00938962 0.07356703 0.76471329 ... 0.58797035 0.4297475  0.67801353]
  [0.92809535 0.59381085 0.04144937 ... 0.01449058 0.19131355 0.6085249 ]
  [0.10534799 0.28499207 0.57445079 ... 0.66163029 0.8535575  0.56275341]]

 [[0.02763442 0.17184316 0.46725657 ... 0.70086969 0.63825856 0.40293301]
  [0.7541731  0.228323

#**NUMPY - 9 Como mudar um formato de um array**
reshape/flatten/hsplit/vsplit

In [3]:
import numpy as np
x = np.arange(0,20)
print("\nArray de 1 de dimensão")
print(x)
print(x.shape)

print("\nArray de 4 de dimensões")
x2 = np.reshape(x,(4,5))
print(x2)
print(x2.shape)

print("\nArray de 1 de dimensões de novo")
x3 = x2.flatten()
print(x3)
print(x3.shape)

print("\n 4 Array de 1 dimensão e 5 elementos ")
x4= np.hsplit(x3,5)
print(x4)
print(x4[0])


Array de 1 de dimensão
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)

Array de 4 de dimensões
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)

Array de 1 de dimensões de novo
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)

 4 Array de 1 dimensão e 5 elementos 
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11]), array([12, 13, 14, 15]), array([16, 17, 18, 19])]
[0 1 2 3]


#**NUMPY - 10º Operações Matemáticas com um array**
soma/subtração/multiplicação/divisão

sum/min/max

In [4]:
import numpy as np

x = np.array([[1,2,3],[6,5,3],[9,9,9]])
print(f"Array x\n {x}")

x = x + 2
print(f"\nSomar  cada elemente com  2\n {x}")


x = x - 5
print("\nSubtrair  cada elemente com  5")
print(x)


x = x * 4
print("\nMultiplicar cada elemente por  4")
print(x)


x = x / 2
print("\nDividir cada elemente por  2")
print(x)


y = np.arange(1,10)
y = np.reshape(y,(3,3))
print(f"\nArray y: \n{y}")

w = x + y
print(f'\n Array w: \n{w}')

w = x / y
print(f'\n Array w: \n{w}')

z = np.sum(y,axis=0)
print(f'\n Somatório na vertical y: \n{z}')

z = np.sum(y,axis=1)
print(f'\n Somatório na horizontal y: \n{z}')

z = np.sum(y)
print(f'\n Somatório y: \n{z}')

z = np.min(y)
print(f'\n Somatório y: \n{z}')

z = np.max(y)
print(f'\n Somatório y: \n{z}')



Array x
 [[1 2 3]
 [6 5 3]
 [9 9 9]]

Somar  cada elemente com  2
 [[ 3  4  5]
 [ 8  7  5]
 [11 11 11]]

Subtrair  cada elemente com  5
[[-2 -1  0]
 [ 3  2  0]
 [ 6  6  6]]

Multiplicar cada elemente por  4
[[-8 -4  0]
 [12  8  0]
 [24 24 24]]

Dividir cada elemente por  2
[[-4. -2.  0.]
 [ 6.  4.  0.]
 [12. 12. 12.]]

Array y: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 Array w: 
[[-3.  0.  3.]
 [10.  9.  6.]
 [19. 20. 21.]]

 Array w: 
[[-4.         -1.          0.        ]
 [ 1.5         0.8         0.        ]
 [ 1.71428571  1.5         1.33333333]]

 Somatório na vertical y: 
[12 15 18]

 Somatório na horizontal y: 
[ 6 15 24]

 Somatório y: 
45

 Somatório y: 
1

 Somatório y: 
9


#**NUMPY - 11 Salvando um Array num Arquivo .txt**
Parâmetros fmt, dtype, delimiter

In [10]:
import numpy as np

x = np.arange(27)
x = x.reshape((3,3,3))
print(f'tensor 3x3x3:\n {x}')

y = x.flatten()
print(f'\nvetor de 27 posições:\n {y}')
np.savetxt('arrayTeste.txt', y,fmt= '%d', delimiter = ';')

z= np.loadtxt('arrayTeste.txt',dtype = np.int8 ,delimiter = ';',)

print(f'\narquivo recuperado e carregado para dentro do programa:\n {z} \ncom o seguinte tipo de dado: {(z.dtype)}')

tensor 3x3x3:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

vetor de 27 posições:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]

arquivo recuperado e carregado para dentro do programa:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26] 
com o seguinte tipo de dado: int8


#**PLOTLY - 1º Abrindo a Documentação da Bilioteca**

#**PLOTLY - 2º Criando arrays para montar os gráficos**

In [11]:
import numpy as np

a = 3/4;
b = 2/4;
c = 1/4;
soma_a = np.ones(20);
soma_b = np.ones(20);
soma_c = np.ones(20);
for i in range (1,soma_a.size):
  soma_a[i] = soma_a[i-1] + a**i;
  soma_b[i] = soma_b[i-1] + b**i;
  soma_c[i] = soma_c[i-1] + c**i;

np.savetxt('soma_a.txt', soma_a,fmt= '%f', delimiter = ';')
np.savetxt('soma_b.txt', soma_b,fmt= '%f', delimiter = ';')
np.savetxt('soma_c.txt', soma_c,fmt= '%f', delimiter = ';')



# **PLOTLY - 3º Recuperando arquivos e plotando o primeiro gráfico**

In [25]:
import numpy as np
import plotly.express as np
array_a_axis_y = np.loadtxt("soma_a.txt",dtype=np.float64, delimiter= ';')
fig = px.scatter(array_a_axis_y)
fig.show()

ModuleNotFoundError: No module named 'plotly'

# **PLOTLY - 4º Recuperando arquivos e plotando os três gráficos gráfico**

In [ ]:
import numpy as np
import plotly.express as px
array_a_axis_y = np.loadtxt("soma_a.txt",dtype=np.float64, delimiter= ';')
array_b_axis_y = np.loadtxt("soma_b.txt",dtype=np.float64, delimiter= ';')
array_c_axis_y = np.loadtxt("soma_c.txt",dtype=np.float64, delimiter= ';')


array_abc_axis_y = np.vstack((array_a_axis_y,array_b_axis_y,array_c_axis_y))
print(array_abc_axis_y)
array_abc_axis_y = array_abc_axis_y.transpose()
print(array_abc_axis_y)
fig = px.line(array_abc_axis_y, labels= "teste",title="Somatório")
fig.show()

[[1.       1.75     2.3125   2.734375 3.050781 3.288086 3.466064 3.599548
  3.699661 3.774746 3.831059 3.873295 3.904971 3.928728 3.946546 3.95991
  3.969932 3.977449 3.983087 3.987315]
 [1.       1.5      1.75     1.875    1.9375   1.96875  1.984375 1.992188
  1.996094 1.998047 1.999023 1.999512 1.999756 1.999878 1.999939 1.999969
  1.999985 1.999992 1.999996 1.999998]
 [1.       1.25     1.3125   1.328125 1.332031 1.333008 1.333252 1.333313
  1.333328 1.333332 1.333333 1.333333 1.333333 1.333333 1.333333 1.333333
  1.333333 1.333333 1.333333 1.333333]]
[[1.       1.       1.      ]
 [1.75     1.5      1.25    ]
 [2.3125   1.75     1.3125  ]
 [2.734375 1.875    1.328125]
 [3.050781 1.9375   1.332031]
 [3.288086 1.96875  1.333008]
 [3.466064 1.984375 1.333252]
 [3.599548 1.992188 1.333313]
 [3.699661 1.996094 1.333328]
 [3.774746 1.998047 1.333332]
 [3.831059 1.999023 1.333333]
 [3.873295 1.999512 1.333333]
 [3.904971 1.999756 1.333333]
 [3.928728 1.999878 1.333333]
 [3.946546 1.999939

# **PLOTLY - 5º Utilizando plotly.graph_objects**


In [9]:
import numpy as np
import plotly.graph_objects as go
array_a_axis_y = np.loadtxt("soma_a.txt",dtype=np.float64, delimiter= ';')
array_b_axis_y = np.loadtxt("soma_b.txt",dtype=np.float64, delimiter= ';')
array_c_axis_y = np.loadtxt("soma_c.txt",dtype=np.float64, delimiter= ';')

array_axis_x = np.arange(1,array_a_axis_y.size)
fig = go.Figure()
fig.add_trace(go.Scatter(x= array_axis_x, y= array_a_axis_y,mode='lines', name='Série de 3/4'))
fig.add_trace(go.Scatter(x= array_axis_x, y= array_b_axis_y,mode='markers', name='Série de 2/4'))
fig.add_trace(go.Scatter(x= array_axis_x, y= array_c_axis_y,mode='markers+lines', name='Série de 1/4'))
fig.update_layout(title = "Somatório de Series com frações",
                  xaxis_title = "termos",
                  yaxis_title = "valor")
fig.show()

ModuleNotFoundError: No module named 'plotly'