In [5]:
import numpy as np

In [6]:
num_elementos = 100000000
##lista_elementos = []
##for x in range(num_elemtos):
   ## lista_elementos.append(x)   
##print(lista_elementos[-1])

array_elementos = np.arange(num_elementos)
print(array_elementos[-1])

99999999


In [56]:
array_teste = np.array([0,1,2,3,4,5,6,7,8,9,10])
print(f'criação de array: {array_teste}')
print(f'criação de array: {np.ones([10])}')
print(f'criação de array: {np.zeros([10])}')
print(f'criação de array: {np.empty([5])}')
print(f'criação de array: {np.arange(15)}')
print(f'criação de array: {np.linspace(0,40, num = 41)}')


criação de array: [ 0  1  2  3  4  5  6  7  8  9 10]
criação de array: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
criação de array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
criação de array: [7.74860419e-304 7.74860419e-304 7.74860419e-304 7.74860419e-304
 7.74860419e-304]
criação de array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
criação de array: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40.]


In [65]:
num_elementos = 1000000000
array_performance = np.zeros(num_elementos,dtype= np.int32)

In [156]:
num_rand = np.random.default_rng()
print((num_rand.random(10) * 2) // 1)

[1. 0. 1. 1. 1. 0. 0. 1. 1. 1.]


In [160]:
num_rand2 = np.random.default_rng()
vetor = num_rand2.random(4)

print(f'Array de vetor: {vetor}')

matriz = num_rand2.random([4,4])
print(f'Array de matriz: {matriz}')

tensor = num_rand2.random([4,4,4])
print(f'Array de tensor: {tensor}')

Array de vetor: [0.39434953 0.57219798 0.92242068 0.45916072]
Array de matriz: [[0.35245986 0.33952437 0.03482838 0.13802513]
 [0.89863752 0.30060623 0.80177399 0.4067385 ]
 [0.54262097 0.13536293 0.04897031 0.48997512]
 [0.15437719 0.09427219 0.53668654 0.94169321]]
Array de tensor: [[[0.15182135 0.86431249 0.09631138 0.58347291]
  [0.08227168 0.04126558 0.01816066 0.39230974]
  [0.90445936 0.17410559 0.76229446 0.70375246]
  [0.84567312 0.4658986  0.06657159 0.51879217]]

 [[0.63494886 0.36641327 0.13723324 0.74251117]
  [0.35294709 0.4414474  0.7085625  0.67220272]
  [0.39627791 0.53710841 0.30018283 0.69084254]
  [0.25528989 0.84518657 0.64659964 0.98170573]]

 [[0.48123034 0.36343861 0.41503269 0.67769233]
  [0.87457917 0.77305047 0.02417674 0.93832658]
  [0.29042739 0.86999825 0.39452798 0.95996992]
  [0.09039741 0.2587414  0.86858535 0.018816  ]]

 [[0.27557496 0.78371589 0.46131233 0.21959958]
  [0.74826068 0.07530171 0.12920518 0.12767077]
  [0.88267966 0.80488073 0.0532458  0